version: '3.8'

services:
  host:
    container_name: host
    build: ./host
    ports:
      - "4173:4173"
    networks:
      - mf

  remote:
    container_name: remote
    build: ./remote
    ports:
      - "4174:4174"
    networks:
      - mf

networks:
  mf:
    driver: bridge
