version: '3.8'

services:
  host:
    container_name: host
    build: ./host
    ports:
      - "5173:5173"
    networks:
      - mf

  remote:
    container_name: remote
    build: ./remote
    ports:
      - "5174:5174"
    networks:
      - mf

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - mf

networks:
  mf:
    driver: bridge